---
- name: Configuration de la VM Ubuntu
  hosts: ubuntu
  become: yes  # Exécution des tâches avec sudo
  tasks:
    - name: Installer le paquet vim
      apt:
        name: vim
        state: present
        update_cache: yes

    - name: Créer un utilisateur
      user:
        name: nouvelutilisateur
        state: present
        shell: /bin/bash
        groups: sudo
        password: "{{ 'MotDePasseSecret' | password_hash('sha512') }}"
